Models/CountStock.cs
namespace StockMarketApp.Models
{
    public class CountStock
    {
        public int Count { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace StockMarketApp.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/StockMarket.cs
using System.ComponentModel.DataAnnotations;

namespace StockMarketApp.Models
{
    public class StockMarket
    {
        [Key]
        public int Id { get; set; }
        public DateOnly Date { get; set; }  
        public string Trade_Code {  get; set; }
        public double High {  get; set; }
        public double Low { get; set; }
        public double Open {  get; set; }
        public double Close { get; set; }
        public string Volume { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StockMarketApp.Models;
using System.Diagnostics;

namespace StockMarketApp.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/JsonController.cs
using Bulky.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using StockMarketApp.Models;
using StockMarketApp.Utlity;
using System;

namespace StockMarketApp.Controllers
{
    public class JsonController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public JsonController(IUnitOfWork unitOfWork)
        { 
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(StockMarket newstock)
        {
            var stock = JsonHelper.ReadFromJsonFile<StockMarket>();
            var cnt = JsonHelper.ReadCountJsonFile();
            cnt.Count = cnt.Count + 1;
            newstock.Id = cnt.Count;    
            stock.Add(newstock);
            JsonHelper.WriteToJsonFile(stock);
            JsonHelper.WriteToCountJsonFile(cnt);
            return RedirectToAction("Index");
        }
        
        public IActionResult Upsert(int? id)
        {
            if (id == null || id ==0)
            {
                return View(new StockMarket());
            }
            else
            {
                var stocks = JsonHelper.ReadFromJsonFile<StockMarket>();
                var stock = stocks.FirstOrDefault(u => u.Id == id);
                if (stock == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(stock);
                }
            }
            
        }
        [HttpPost]
        public IActionResult Upsert(StockMarket updatestock)
        {


            if (ModelState.IsValid)
            {
                if (updatestock.Id == 0)
                {
                    var stock = JsonHelper.ReadFromJsonFile<StockMarket>();
                    var cnt = JsonHelper.ReadCountJsonFile();
                    cnt.Count = cnt.Count + 1;
                    updatestock.Id = cnt.Count;
                    stock.Add(updatestock);
                    JsonHelper.WriteToJsonFile(stock);
                    JsonHelper.WriteToCountJsonFile(cnt);
                    TempData["success"] = "Stock Created Successfuly";
                    return RedirectToAction("Index");
                }
                else
                {
                    var stocks = JsonHelper.ReadFromJsonFile<StockMarket>();
                    var stock = stocks.FirstOrDefault(u => u.Id == updatestock.Id);
                    stock.Id = updatestock.Id;
                    stock.Date = updatestock.Date;
                    stock.Trade_Code = updatestock.Trade_Code;
                    stock.High = updatestock.High;
                    stock.Low = updatestock.Low;
                    stock.Open = updatestock.Open;
                    stock.Close = updatestock.Close;
                    stock.Volume = updatestock.Volume;

                    JsonHelper.WriteToJsonFile(stocks);
                    TempData["success"] = "Stock Update Successfuly";
                    return RedirectToAction("Index");
                }

            }
            else
            {
                return View(updatestock);
            }
        }
        public IActionResult Chart()
        {
            return View();
        }


        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            List<StockMarket> ObjList = JsonHelper.ReadFromJsonFile<StockMarket>();
            
            return Json(new { data = ObjList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var stocks = JsonHelper.ReadFromJsonFile<StockMarket>();
            var stock = stocks.FirstOrDefault(u => u.Id == id);
            if (stock == null)
            {
                return NotFound();
            }
            stocks.Remove(stock);
            JsonHelper.WriteToJsonFile<StockMarket>(stocks);
            return NoContent();
        }
        #endregion
    }
}

Controllers/SqlController.cs
using Bulky.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using StockMarketApp.Models;

namespace StockMarketApp.Controllers
{
    public class SqlController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public SqlController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                return View(new StockMarket());
            }
            else
            {
                StockMarket stockMarket = _unitOfWork.stockRepositoty.Get(u => u.Id == id);
                return View(stockMarket);
            }

        }
        [HttpPost]
        public IActionResult Upsert(StockMarket updatestock)
        {
            if (ModelState.IsValid)
            {


                if (updatestock.Id == 0)
                {
                    _unitOfWork.stockRepositoty.Add(updatestock);
                }
                else
                {
                    _unitOfWork.stockRepositoty.Update(updatestock);
                }

                _unitOfWork.Save();
                TempData["success"] = "Company Created Successfuly";
                return RedirectToAction("Index");
            }
            else
            {

                return View(updatestock);
            }

        }
        public IActionResult Chart()
        {
            return View();
        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            List<StockMarket> objCompanyList = _unitOfWork.stockRepositoty.GetAll().ToList();
            return Json(new { data = objCompanyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var StockToBeDeleted = _unitOfWork.stockRepositoty.Get(u => u.Id == id);
            if (StockToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.stockRepositoty.Remove(StockToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Json/Chart.cshtml
<div class="card shadow border-0 mt-4 mb-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Stock Chart</h2>
                <hr />
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        
        <div>
            <canvas id="myChart"></canvas>
            <canvas id="myChartBar"></canvas>
            <select id="dropdown-container">
                <option>-Select--</option>
            </select>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/js/datachart.js"></script>
}

Views/Json/Index.cshtml
<div class="card shadow border-0 mt-4 mb-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Stock List</h2>
                <hr />
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="co-6 text-end">
                <a asp-action="Upsert" class="btn btn-dark">
                    Create New Stock
                    <i class="bi bi-plus-circle"></i>
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped" style="width:100%;">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Trade Code</th>
                    <th>High</th>
                    <th>Low</th>
                    <th>Open</th>
                    <th>Colse</th>
                    <th>Volume</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts{
    <script src="~/js/stockmarket.js"></script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockMarketApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="~/StockMarketApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockMarketApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                JSON
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-controller="Json" asp-action="Index">List</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Json" asp-action="Chart">Chart</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                SQL
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-controller="Sql" asp-action="Index">List</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Sql" asp-action="Chart">Chart</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StockMarketApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="//cdn.datatables.net/2.0.8/js/dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

Views/Sql/Chart.cshtml
<div class="card shadow border-0 mt-4 mb-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Stock Chart</h2>
                <hr />
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        
        <div>
            <canvas id="myChart"></canvas>
            <canvas id="myChartBar"></canvas>
            <select id="dropdown-container">
                <option>-Select--</option>
            </select>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/js/datachartsql.js"></script>
}

Views/Sql/Index.cshtml
<div class="card shadow border-0 mt-4 mb-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Stock List</h2>
                <hr />
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="co-6 text-end">
                <a asp-action="Upsert" class="btn btn-dark">
                    Create New Stock
                    <i class="bi bi-plus-circle"></i>
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped" style="width:100%;">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Trade Code</th>
                    <th>High</th>
                    <th>Low</th>
                    <th>Open</th>
                    <th>Colse</th>
                    <th>Volume</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts {
    <script src="~/js/stockmarketsql.js"></script>
}

Views/Sql/Upsert.cshtml
@model StockMarket

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id != 0 ? "Update" : "Create") Stock</h2>
                <hr />
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" type="hidden" />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Date" type="date" class="form-control border-0 shadow" />
                            <label asp-for="Date" class="ms-2">Date</label>
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Trade_Code" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Trade_Code" class="ms-2">Trade Code</label>
                            <span asp-validation-for="Trade_Code" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="High" type="text" class="form-control border-0 shadow" />
                            <label asp-for="High" class="ms-2">High</label>
                            <span asp-validation-for="High" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Low" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Low" class="ms-2">Low</label>
                            <span asp-validation-for="Low" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Open" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Open" class="ms-2">Open</label>
                            <span asp-validation-for="Open" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Close" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Close" class="ms-2">Close</label>
                            <span asp-validation-for="Close" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Volume" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Volume" class="ms-2">Volume</label>
                            <span asp-validation-for="Volume" class="text-danger"></span>
                        </div>
                        <div class="row m-3">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                                }

                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Json" asp-action="Index" class="btn btn-outline-primary border form-control" style="width:150px">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}